spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_eed8450e812a01e?reconnect=true"
    username: "bda3bf637497b7"
    password: "ee5ffb70"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  basic:
    enabled: false

server:
  port: 8082
 